// <auto-generated />
using System;
using System.Collections.Generic;
using LunchSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LunchSync.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LunchSync.Core.Modules.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cognito_sub");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CognitoSub")
                        .IsUnique()
                        .HasDatabaseName("idx_users_cognito_sub");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CoverageRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(250)
                        .HasColumnName("coverage_radius_meters");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("LandmarkLat")
                        .HasColumnType("double precision")
                        .HasColumnName("landmark_lat");

                    b.Property<double?>("LandmarkLon")
                        .HasColumnType("double precision")
                        .HasColumnName("landmark_lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dishes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dishes_name");

                    b.ToTable("dishes", null, t =>
                        {
                            t.HasCheckConstraint("chk_profile_valid", "jsonb_typeof(profile) = 'object'");
                        });
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("text")
                        .HasColumnName("google_maps_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_tier");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Admin")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.RestaurantCollection", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.HasKey("RestaurantId", "CollectionId")
                        .HasName("pk_restaurant_collections");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("idx_rc_collection");

                    b.ToTable("restaurant_collections", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.RestaurantDish", b =>
                {
                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.HasKey("RestaurantId", "DishId")
                        .HasName("pk_restaurant_dishes");

                    b.HasIndex("DishId")
                        .HasDatabaseName("idx_rd_dish");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("idx_rd_restaurant");

                    b.ToTable("restaurant_dishes", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("text")
                        .HasColumnName("google_maps_url");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PriceTier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("price_tier");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("restaurant_name");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_submissions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_submissions_user");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.SubmissionDish", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid")
                        .HasColumnName("dish_id");

                    b.HasKey("SubmissionId", "DishId")
                        .HasName("pk_submission_dishes");

                    b.HasIndex("DishId")
                        .HasDatabaseName("ix_submission_dishes_dish_id");

                    b.ToTable("submission_dishes", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.SubmissionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submission_photos");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("idx_submission_photos_sub");

                    b.ToTable("submission_photos", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Sessions.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nickname");

                    b.PrimitiveCollection<List<float>>("PrefVector")
                        .HasColumnType("jsonb")
                        .HasColumnName("pref_vector");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voted_at");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_participants_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_participants_user_id");

                    b.HasIndex("SessionId", "Nickname")
                        .IsUnique()
                        .HasDatabaseName("ix_participants_session_id_nickname");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Sessions.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<Guid>>("BoomEliminatedIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("boom_eliminated_ids");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("FinalRestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("final_restaurant_id");

                    b.PrimitiveCollection<List<float>>("GroupVector")
                        .HasColumnType("jsonb")
                        .HasColumnName("group_vector");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("pin");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_tier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<Guid>>("TopDishIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("top_dish_ids");

                    b.PrimitiveCollection<List<Guid>>("TopRestaurantIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("top_restaurant_ids");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VotingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voting_started_at");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_sessions_collection_id");

                    b.HasIndex("FinalRestaurantId")
                        .HasDatabaseName("ix_sessions_final_restaurant_id");

                    b.HasIndex("HostId")
                        .HasDatabaseName("idx_sessions_host");

                    b.HasIndex("Pin")
                        .HasDatabaseName("idx_sessions_pin");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sessions_status")
                        .HasFilter("status NOT IN ('done')");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Dish", b =>
                {
                    b.OwnsOne("LunchSync.Core.Common.ValueObjects.DishProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("DishId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<double>("Communal")
                                .HasColumnType("double precision");

                            b1.Property<double>("FlavorIntensity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Healthy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Heaviness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Novelty")
                                .HasColumnType("double precision");

                            b1.Property<double>("Soupy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Spicy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double precision");

                            b1.Property<double>("TextureComplexity")
                                .HasColumnType("double precision");

                            b1.Property<double>("TimeRequired")
                                .HasColumnType("double precision");

                            b1.HasKey("DishId");

                            b1.ToTable("dishes");

                            b1
                                .ToJson("profile")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DishId")
                                .HasConstraintName("fk_dishes_dishes_id");
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.RestaurantCollection", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Collection", "Collection")
                        .WithMany("RestaurantCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_collections_collections_collection_id");

                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Restaurant", "Restaurant")
                        .WithMany("RestaurantCollections")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_collections_restaurants_restaurant_id");

                    b.Navigation("Collection");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.RestaurantDish", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Dish", "Dish")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_dishes_dishes_dish_id");

                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Restaurant", "Restaurant")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_dishes_restaurants_restaurant_id");

                    b.Navigation("Dish");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Submission", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.Auth.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.SubmissionDish", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Dish", "Dish")
                        .WithMany("SubmissionDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_dishes_dishes_dish_id");

                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Submission", "Submission")
                        .WithMany("SubmissionDishes")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_dishes_submissions_submission_id");

                    b.Navigation("Dish");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.SubmissionPhoto", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Submission", "Submission")
                        .WithMany("Photos")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_photos_submissions_submission_id");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Sessions.Entities.Participant", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.Sessions.Entities.Session", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_sessions_session_id");

                    b.HasOne("LunchSync.Core.Modules.Auth.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_participants_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Sessions.Entities.Session", b =>
                {
                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_collections_collection_id");

                    b.HasOne("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("FinalRestaurantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sessions_restaurants_final_restaurant_id");

                    b.HasOne("LunchSync.Core.Modules.Auth.Entities.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_host_id");

                    b.Navigation("Collection");

                    b.Navigation("Host");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Auth.Entities.User", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Collection", b =>
                {
                    b.Navigation("RestaurantCollections");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Dish", b =>
                {
                    b.Navigation("RestaurantDishes");

                    b.Navigation("SubmissionDishes");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Restaurant", b =>
                {
                    b.Navigation("RestaurantCollections");

                    b.Navigation("RestaurantDishes");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.RestaurantsAndDishes.Entities.Submission", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("SubmissionDishes");
                });

            modelBuilder.Entity("LunchSync.Core.Modules.Sessions.Entities.Session", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
